//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Note
    {
        public short NID { get; set; }
        public string OgrenciAdi { get; set; }
        public string OgrenciNumarasi { get; set; }
        public Nullable<byte> Vize { get; set; }
        public Nullable<byte> Final { get; set; }
        public Nullable<byte> But { get; set; }
        public Nullable<short> CSID { get; set; }
        public string DersAdi { get; set; }
    
        public virtual StudentCourse StudentCourse { get; set; }
    }
}
